console.log('🔗 How to Get Your MongoDB Atlas Connection String:');
console.log('');
console.log('1. 📱 Go to MongoDB Atlas Dashboard (https://cloud.mongodb.com)');
console.log('2. 🏢 Select your "tyma-medicore" cluster');
console.log('3. 🔗 Click the "Connect" button');
console.log('4. 💻 Choose "Connect your application"');
console.log('5. 📋 Copy the connection string');
console.log('');
console.log('🔧 Connection String Format:');
console.log('mongodb+srv://<username>:<password>@<cluster-url>/tyma-medicore?retryWrites=true&w=majority');
console.log('');
console.log('📝 What to Replace:');
console.log('- <username>: Your MongoDB Atlas username');
console.log('- <password>: Your MongoDB Atlas password');
console.log('- <cluster-url>: Your cluster URL (keep as is)');
console.log('- <dbname>: Replace with "tyma-medicore"');
console.log('');
console.log('📁 Create a .env file in the backend folder with:');
console.log('MONGO_URI=your_connection_string_here');
console.log('PORT=5000');
console.log('JWT_SECRET=your_secret_key_here');
console.log('');
console.log('🚀 After creating .env, run:');
console.log('npm run setup-db'); 